### PR TITLE
make patches relative to respective package dirs

### PR DESCRIPTION
**Pull request by cstrahan**
This makes the patches relative to their corresponding package directories.

### CODE REVIEW

**Comment by luite** [comment]
These are packages that are actually not submodules, since they've been copied from the GHC source tree. All patches are relative to the top level of their respective git repositories, `ghcjs-boot` uses `git apply` to apply them.

Have you found any problems with `ghcjs-boot` with these patches?

**Comment by cstrahan** [comment]
> Have you found any problems with ghcjs-boot with these patches?

Git would fail with an error along the lines of "boot/base/GHC/Conc.hs not found", and this patch fixed things for me.

Now that I think of it, I think I understand what's going on. When we pull the source for ghcjs-boot in Nixpkgs, we don't keep the `.git` directory around (because it introduces non-determinism). However, you're already `cd`ing into the proper directory before applying the patches, so this patch fixes things in our `.git`less environment. However, I don't know if this introduces problems when the `.git` directory does exist.

**Comment by luite** [comment]
the packages copied from the GHC tree are `base`, `integer-gmp`, and `template-haskell`, they're unlikely to change (unless GHC itself also pulls in more packages into its own git tree).

Is it possible to change the patch command used by Nixpkgs to strip more path sections for these packages?

**Comment by cstrahan** [comment]
> Is it possible to change the patch command used by Nixpkgs to strip more path sections for these packages?

Yep, that's perfectly doable.

**Pull request closed without merging**
